from anytree import Node, RenderTree

root = Node("SISTEMA DE ARCHIVOS DE LINUX")

level_1_child_1 = Node("bin", parent=root)
level_1_child_2 = Node("boot", parent=root)
level_1_child_3 = Node("dev", parent=root)
level_1_child_4 = Node("etc", parent=root)
level_1_child_5 = Node("home", parent=root)
level_1_child_6 = Node("initrd", parent=root)
level_1_child_7 = Node("lib", parent=root)
level_1_child_8 = Node("lost+found", parent=root)
level_1_child_9 = Node("media", parent=root)
level_1_child_10 = Node("mnt", parent=root)
level_1_child_11 = Node("opt", parent=root)
level_1_child_12 = Node("proc", parent=root)
level_1_child_13 = Node("root", parent=root)
level_1_child_14 = Node("sbin", parent=root)
level_1_child_15 = Node("srv", parent=root)
level_1_child_16 = Node("sys", parent=root)
level_1_child_17 = Node("tmp", parent=root)
level_1_child_18 = Node("usr", parent=root)
level_1_child_19 = Node("var", parent=root)

level_2_child_1 = Node("Aplicaciónes binarias importantes", parent=level_1_child_1)
level_2_child_1 = Node("Ficheros de configuración del arranque", parent=level_1_child_2)
level_2_child_1 = Node("Ficheros de dispositivo", parent=level_1_child_3)
level_2_child_1 = Node("Script de arranque", parent=level_1_child_4)
level_2_child_1 = Node("Directorios personales", parent=level_1_child_5)
level_2_child_1 = Node("Usado cuando se crea un proceso de arranque", parent=level_1_child_6)
level_2_child_1 = Node("Librerias del sistema", parent=level_1_child_7)
level_2_child_1 = Node("Perdido+Encontrado", parent=level_1_child_8)
level_2_child_1 = Node("Particiones montadas", parent=level_1_child_9)
level_2_child_1 = Node("Sistema de archivos montados automaticamente en el disco duro", parent=level_1_child_10)
level_2_child_1 = Node("Sistema de archivos montados manualmente", parent=level_1_child_11)
level_2_child_1 = Node("Proporciona una ubicación donde instalar aplicaciónes", parent=level_1_child_12)
level_2_child_1 = Node("Directorio dinamico", parent=level_1_child_13)
level_2_child_1 = Node("Directorio Personal", parent=level_1_child_14)
level_2_child_1 = Node("Binarios importantes del sitema", parent=level_1_child_15)
level_2_child_1 = Node("Puede contener archivos que sirven para otros sistemas", parent=level_1_child_16)
level_2_child_1 = Node("Archivos del sistema", parent=level_1_child_17)
level_2_child_1 = Node("Archivos temporales", parent=level_1_child_18)
level_2_child_1 = Node("Aplicaciónes y archivos a los que pueden acceder la mayoria de users", parent=level_1_child_19)

for pre, fill, node in RenderTree(root):
    print("%s%s" % (pre, node.name))